### PR TITLE
Windows support and cross platform import/export

### PR DESCRIPTION
**Pull request by colthreepv**
This is definitely an hard to merge PR, but I had to fix it for my own need.

The commits fixes different problems:
- windows support, it just _wasn't there_ because of not using platform-agnostic node API(s)
- cross-platform import/export. Path(s) now get exported in linux format, then during import they get adapted to the destination platform
- minimal styleguide to make this project more contributor-friendly

### CODE REVIEW

**Comment by colthreepv** [comment]
ping @bhurlow - any opinion on this functionality?
I know the PR is more vast than the strict required, but as docker-machine doesn't seem to support this in the short term, I was hoping to keep this project alive and updated for the foreseeable future

**Comment by colthreepv** [comment]
ping @bhurlow last followup.. I am using these modifications since a month with great success in my workteam

If there is no interest in merging this, I would just do an hard-fork, for having less entropy (as possible) in the world I **really** wish we could communicate and just make a better working `machine-share`

**Comment by bhurlow** [comment]
@colthreepv let's merge it! can u fix the conflict? I'll take your word for it

**Comment by bhurlow** [comment]
@colthreepv still want to merge this in? Needs small resolution on `import.js` rest looks solid

**Comment by colthreepv** [comment]
Okay this PR should be fixed now, please double check on different platforms, 4 eyes are always better than 2

**Comment by bhurlow** [comment]
@colthreepv thank you! Glad to get this incorporated and sorry for the slow pace (see https://github.com/bhurlow/machine-share/issues/19 on repo status)

**Pull request merged**
